language: java
jdk: openjdk8

sudo: false

before_script:
  # get and build protobuf
  - export PROTOBUF_VERSION=2.6.1
  - wget --output-document $HOME/protobuf-$PROTOBUF_VERSION.tar.gz https://github.com/google/protobuf/releases/download/v$PROTOBUF_VERSION/protobuf-$PROTOBUF_VERSION.tar.gz
  - cd $HOME
  - tar xf protobuf-$PROTOBUF_VERSION.tar.gz
  - cd protobuf-$PROTOBUF_VERSION
  - ./configure
  - make -j2
  - cd $TRAVIS_BUILD_DIR

  # configure maven repositories
  - echo "<settings xmlns=\"http://maven.apache.org/SETTINGS/1.0.0\""     >  $HOME/settings.xml
  - echo "  xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\""      >> $HOME/settings.xml
  - echo "  xsi:schemaLocation=\"http://maven.apache.org/SETTINGS/1.0.0"  >> $HOME/settings.xml
  - echo "  https://maven.apache.org/xsd/settings-1.0.0.xsd\">"           >> $HOME/settings.xml
  - echo "  <profiles>"                                                   >> $HOME/settings.xml
  - echo "    <profile>"                                                  >> $HOME/settings.xml
  - echo "      <id>babudb-dev</id>"                                      >> $HOME/settings.xml
  - echo "      <repositories>"                                           >> $HOME/settings.xml
  - echo "        <repository>"                                           >> $HOME/settings.xml
  - echo "          <id>central</id>"                                     >> $HOME/settings.xml
  - echo "          <url>http://repo.maven.apache.org/maven2</url>"       >> $HOME/settings.xml
  - echo "        </repository>"                                          >> $HOME/settings.xml
  - echo "        <repository>"                                           >> $HOME/settings.xml
  - echo "          <id>xtreemfs-repository</id>"                         >> $HOME/settings.xml
  - echo "          <url>https://xtreemfs.github.io/xtreemfs/maven</url>" >> $HOME/settings.xml
  - echo "          <snapshots><enabled>true</enabled></snapshots>"       >> $HOME/settings.xml
  - echo "        </repository>"                                          >> $HOME/settings.xml
  - echo "      </repositories>"                                          >> $HOME/settings.xml
  - echo "    </profile>"                                                 >> $HOME/settings.xml
  - echo "  </profiles>"                                                  >> $HOME/settings.xml
  - echo "</settings>"                                                    >> $HOME/settings.xml

  # build jars without tests, as they depend on the built jars
  - mvn --settings $HOME/settings.xml --activate-profiles babudb-dev --file $TRAVIS_BUILD_DIR/java/pom.xml -Dprotoc.bin=$HOME/protobuf-$PROTOBUF_VERSION/src/protoc -Dprotoc.include=$HOME/protobuf-$PROTOBUF_VERSION/src -DskipTests install

  # build C++ tests
  - mkdir -p $TRAVIS_BUILD_DIR/cpp/build
  - cd $TRAVIS_BUILD_DIR/cpp/build
  - cmake ..
  - make -j2
  - cd $TRAVIS_BUILD_DIR

script:
  # run Java tests
  - mvn --settings $HOME/settings.xml --activate-profiles babudb-dev --file $TRAVIS_BUILD_DIR/java/pom.xml -Dprotoc.bin=$HOME/protobuf-$PROTOBUF_VERSION/src/protoc -Dprotoc.include=$HOME/protobuf-$PROTOBUF_VERSION/src test

  # FIXME: run C++ tests
  # - cd $TRAVIS_BUILD_DIR/cpp/build
  # - ./babudb_tests
  # - cd $TRAVIS_BUILD_DIR
